# -*- coding: utf-8 -*-
"""Program 1: Picnic Pizza.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cKwLnWle5mLUwKu8QVpn4c15m9DjXEfE

```
# Program 1: Picnic Pizza (DDL: 6/10)
```
"""

import math

time_hour = int(input("What hour is the pizza ordered?")) #Input always give you a string
time_minute = int(input("What minute is the pizza ordered?"))

#Step1: crust
CRUST_TIME = 30 #sec.

#If no optional toppings are ordered, the pizza still passes through those stations on the conveyor belt, but no topping is dispensed.

#Step2_station1: (mandatory)sauce 
SAUCE_TIME = 10 #sec.

#Step3_station2: (mandatory)cheese
CHEESE_TIME = 10 #sec.

#Step4_station3: (optional)pepperoni
PEPPERONI_TIME = 10 #sec.

#Step5_station4: (optional)ham
HAM_TIME = 10 #sec.

topping_count = (input("How many toppings? (0, 1, or 2)"))
name_of_toppings = input("Names of Toppings: <enter> for none, or name them: ")

#Step6: bake
BASE_COOKING_TIME = 720 #sec.
ADDITIONAL_COOKING_TIME = 60 * int(topping_count)
TOTAL_COOKING_TIME = BASE_COOKING_TIME + ADDITIONAL_COOKING_TIME

#Step7: box and slice
BOX_SLICE_TIME = 60 #sec.
TRAVEL_TIME = 5 #sec.
TOTAL_TRAVEL_TIME = TRAVEL_TIME * (7-1) + BOX_SLICE_TIME #7 stations

#complete time 
  #Hour
COMPLETE_TIME_MINUTE = math.ceil((CRUST_TIME + SAUCE_TIME + CHEESE_TIME + PEPPERONI_TIME + HAM_TIME + TOTAL_COOKING_TIME + TOTAL_TRAVEL_TIME)/60)
COMPLETE_TIME_HOUR = time_hour + (time_minute + COMPLETE_TIME_MINUTE) // 60

#making 24:00 = 00:00
TIME_READY_HOUR = COMPLETE_TIME_HOUR % 24
#If Condition
# if TIME_READY_HOUR > 23:
#  TIME_READY_HOUR = 0 [Dented line to be under if condition]

  #Minute
TIME_READY_MINUTE = (time_minute + COMPLETE_TIME_MINUTE) % 60

#price
BASE_PRICE = 12
ADDITIONAL_PRICING_TIME = 1.25
total_price = BASE_PRICE + ADDITIONAL_PRICING_TIME * int(topping_count)

#adding $ sign and format
#formatted_total_price = "${:.2f}".format(total_price)

#final output 
#print("%d:%02d" % (time_ready_hr, time_ready_min))
#print("Your", name_of_toppings, "pizza will be ready at", str(time_ready_hr).zfill(2), ":", str(time_ready_min).zfill(2))
print("Your", name_of_toppings, "pizza will be ready at", "%02d:%02d" % (TIME_READY_HOUR, TIME_READY_MINUTE))
print("The cost will be", "${:.2f}".format(total_price))